### ISSUE TITLE
짧은 오디오파일의 처리가 가능하도록 코드 구현

### ISSUE THREAD

**Issue by KimYealynn** [kookmin-sw/2018-cap1-7#10]

**Comment by swzoey** [comment]
ceps -> mfcc

def write_ceps(ceps, fn):
    """
    Write the MFCC to separate files to speed up processing.
    """
    base_fn, ext = os.path.splitext(fn)
    data_fn = base_fn + ".ceps"
    np.save(data_fn, ceps)
    print("Written %s"%data_fn)


def create_ceps(fn):
    sample_rate, X = scipy.io.wavfile.read(fn)

    ceps, mspec, spec = mfcc(X)
    write_ceps(ceps, fn)

+++++++++++++++++++++++++++

def write_mfcc(mfcc, fn):
   # Write the MFCC to separate files to speed up processing.
    base_fn, ext = os.path.splitext(fn)
    data_fn = base_fn + ".mfcc"
    np.save(data_fn, mfcc)
    print("Written %s"%data_fn)


def create_mfcc(fn):
    X, sample_rate = librosa.load(fn)
    mfccs = librosa.feature.mfcc(y=X,
                                 sr=sample_rate,
                                 n_mfcc=39,
                                 hop_length=int(sample_rate * 0.01),
                                 n_fft=int(sample_rate * 0.02),
                                 htk=True).T
    write_mfcc(mfccs, fn)

**Comment by swzoey** [comment]
몇몇 소리파일이 인식되지않았던 것으로 판명, 짧은 오디오파일 처리 가능
