### ISSUE TITLE
라즈베리파이 w  를 이용한 시연용 하드웨어 만들기

### ISSUE THREAD

**Issue by GaeulG** [kookmin-sw/2018-cap1-7#119]

**Comment by GaeulG** [comment]
lite로 다운받아서 국가 설정 -> sudo iwlist wlan0 scan 하면 무선 랜 검색됨 -> 연결하기!

**Comment by GaeulG** [comment]
![image](https://user-images.githubusercontent.com/34901822/40583485-ad7a96b2-61ca-11e8-9411-417b30454456.png)

**Comment by GaeulG** [comment]
![image](https://user-images.githubusercontent.com/34901822/40583499-08f57c82-61cb-11e8-9a33-60b22d61df59.png)

**Comment by GaeulG** [comment]
연결 성공했습니다!

**Comment by GaeulG** [comment]
sudo raspi-config -> 3) boot options -> B1) Desktop/ CLI -> B2) Console Autologin 설정

**Comment by GaeulG** [comment]
sudo apt-get install git 한 후 git clone (현재 프로젝트)

**Comment by GaeulG** [comment]
http://feelsoverygood.tistory.com/34

**Comment by KimYealynn** [comment]
![kakaotalk_20180527_153426508](https://user-images.githubusercontent.com/21376911/40585695-1441eb62-61f2-11e8-9e10-cb02e6d90fea.jpg)
![Uploading KakaoTalk_20180527_153425692.jpg…]()

**Comment by GaeulG** [comment]
![img_7572](https://user-images.githubusercontent.com/34901822/40586235-a845c600-61fa-11e8-9ff6-ab2afe921cd4.JPG)
