### ISSUE TITLE
라즈베리파이 OLED에 자막 띄우기

### ISSUE THREAD

**Issue by GaeulG** [kookmin-sw/2018-cap1-7#35]

**Comment by GaeulG** [comment]
현재 자막 띄우는 것 완료했는데, 한글이 뜰지는 테스트 해봐야겠네용

**Comment by GaeulG** [comment]
오류 : 한글이 안뜸
해결 방안 : 코드 분석 후 추가 코드 삽입

**Comment by GaeulG** [comment]
@sungho123 디스플레이에 한글 띄우는 법을 알아야 할 거 같아요ㅠ
https://www.systutorials.com/4670/ascii-table-and-ascii-code/ 
http://www.cplusplus.com/forum/general/111544/ 
참고한 url들입니다~

**Comment by sungho123** [comment]
참고할게요

**Comment by GaeulG** [comment]
현재 라즈베리파이에서 바탕화면에 있는 파일인 textshow2.c를 가지고, 컴파일하여 실행 파일 show 를 생성하였습니다.
이 파일을 라즈베리파이 viewtiful / GoogleCloudSDK / python-doc-samples / speech 파일 내 transcribe_streaming_mic_gaeul.py 파일을 실행하면 오류 없이 자막이 뜹니다.

**Comment by GaeulG** [comment]
@sungho123 나중에 작업할 때 확인해주세요 ~

**Comment by GaeulG** [comment]
우선은 영어 자막으로 진행하겠습니다! 한글을 출력할 방법은 우선 제품이 어느 정도 완성되고 찾아봐야해야할듯해요
