### ISSUE TITLE
마이크 모듈 변경

### ISSUE THREAD

**Issue by swzoey** [kookmin-sw/2018-cap1-7#38]

**Comment by swzoey** [comment]
![img_0511](https://user-images.githubusercontent.com/12928693/39750002-14a12058-52ef-11e8-9908-48e6d7556330.JPG)

**Comment by KimYealynn** [comment]
고감도 증폭 DSLR 마이크 [R-4059A3] : 주변소리 작은 소리까지 잘 인식하나 잡음이 너무 많은 문제.

**Comment by KimYealynn** [comment]
에듀티지 고감도 핀마이크 [ETM-006] : 주변소리 작은 소리까지 잘 인식하나 잡음이 너무 많은 문제, R-4059 모델 보다는 조금 덜 함
