### ISSUE TITLE
기능 별 실행 순서 정하기

### ISSUE THREAD

**Issue by swzoey** [kookmin-sw/2018-cap1-7#91]
1) 소리 크기
2) 음성 텍스트 변환
3) 실시간 소리 분류

**Comment by GaeulG** [comment]
지금 제가 구현한 것은 흰색 버튼을 누르면 2. 음성 텍스트 변환 / 노란색 버튼을 누르면 1. 소리 크기가 실행이 됩니다

**Comment by swzoey** [comment]
먼저 라즈베리 파이를 실행시켰을 때 음성텍스트 변환은 버튼을 눌렀을 때만 실행되고, 소리크기와 실시간 소리 분류를 어떻게 실행을 해야 할지 의논해 봐야 합니다.

**Comment by GaeulG** [comment]
사실 이상적인 것은 실시간 소리 분류를 항상 실행되도록 하는 것이긴 한데..

**Comment by swzoey** [comment]
실시간 소리 분류를 항상 실행하게 되면 소리 크기는 버튼을 누를 때 실행하게 되는 건가요?

**Comment by GaeulG** [comment]
넵 제가 지금 생각하는 것은 음성텍스트 변환과 소리 크기를 실행하지 않을 때 <소리 분류 버튼>을 하나 만들어 위험한 소리 인식시에만 화면을 통해 알리는 것이 좋을 듯 합니다.

**Comment by swzoey** [comment]
그러면 소리분류 후 퍼센트 율에 따라서 소리가 어느 정도 (약 7-80% )정확히 판단되었을 때  소리의 종류를 출력하게 하는 것은 어떤가요?

**Comment by GaeulG** [comment]
그걸로 진행해보죠 저는 버튼을 하나 더 만들도록 하겠습니다

**Comment by swzoey** [comment]
알겠습니다

**Comment by swzoey** [comment]
소리 크기가 일정 크기 이상인 경우에 소리 종류를 판단하도록 하였습니다.
